Algoritmo "Comando Caso - Escolhas múltiplas"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/10/2024
Var

   x: literal


Inicio

   escreval("Digite uma letra: ")
   leia(x)
   escolha x
   caso "a"
      escreval("Você digitou a letra A.")
   caso "b"
      escreval("VocÊ digitou a letra B.")
   outrocaso
      escreval("Você digitou uma outra letra.")
   fimescolha


Fimalgoritmo